name: Create Release
run-name: ${{ github.event.pull_request.title }}

on:
  pull_request:
    types:
      - closed

jobs:
  create_release:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Get package name and version
        id: get_package_name_and_version
        run: |
          PACKAGE_NAME=$(echo ${{ github.event.pull_request.head.ref }} | cut -d'/' -f2)
          VERSION=$(echo ${{ github.event.pull_request.head.ref }} | cut -d'/' -f3)
          echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_OUTPUT
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configurationJson: |
            {
              "ignore_labels": [
                "release"
              ],
              "tag_resolver": {
                "method": "semver",
                "filter": {
                  "pattern": "${{ steps.get_package_name_and_version.outputs.PACKAGE_NAME }}@(.+)",
                  "flags": "gu"
                }
              },
            }
      - name: debug
        run: echo '${{ toJSON(steps.build_changelog.outputs) }}'
