name: Create Release
run-name: ${{ github.event.pull_request.title }}

on:
  pull_request:
    types:
      - closed

jobs:
  create_release:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get package name and version
        id: get_package_name_and_version
        run: |
          PACKAGE_NAME=$(echo ${{ github.event.pull_request.head.ref }} | cut -d'/' -f2)
          VERSION=$(echo ${{ github.event.pull_request.head.ref }} | cut -d'/' -f3)
          echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_OUTPUT
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          toTag: ${{ github.event.pull_request.base.sha }}
          configurationJson: |
            {
              "categories": [
                {
                  "title": "Update",
                  "labels": ["${{ steps.get_package_name_and_version.outputs.PACKAGE_NAME }}"]
                }
              ],
              "ignore_labels": [
                "release"
              ],
              "tag_resolver": {
                "method": "semver",
                "filter": {
                  "pattern": "${{ steps.get_package_name_and_version.outputs.PACKAGE_NAME }}@(.+)",
                  "flags": "gu"
                },
                "transformer": {
                  "pattern": "${{ steps.get_package_name_and_version.outputs.PACKAGE_NAME }}@(.+)",
                  "flags": "gu",
                  "target": "$1"
                }
              }
            }
      - name: debug
        run: echo '${{ toJSON(steps.build_changelog.outputs) }}'
      - name: Add comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: commentData } = await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `${${{ steps.build_changelog.outputs.changelog }}}`
            });
            console.log('Comment created:', commentData.html_url);
